### ISSUE TITLE
Add diagrm of how training pipeline works

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_datapipes#106]
## Detailed Description
Would be great to have a diagram of how the pipelines are roughly working.
Perhaps good to start with simple training pipeline

## Possible Implementation
nice flow diagram
- loading data
- picking location
- selecting location fomr input data
- picking to,
- picking t0 in input data
- joining together in batch

**Comment by jacobbieker** [comment]
Yep! Sounds good. Was thinking of also adding some more code examples of the common load+pick location+pick time setup
