### ISSUE TITLE
Write test for training:datamodles

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_datapipes#115]
## Detailed Description
Good to have CI test

## Context
Good ot have tests

## Possible Implementation
Write pytest for `ocf_datapipe.training.datamodules`

**Comment by Plomo-02** [comment]
hello, Is it possible being assigned to this issue?

**Comment by Plomo-02** [comment]
HI peter, a question before start, what you mean for datamodules?

**Comment by peterdudfield** [comment]
Im not sure either, this could be old, so we could close this

**Comment by Plomo-02** [comment]
oh ok, can you guide for an open issue?

**Comment by peterdudfield** [comment]
So there are lots in here - https://github.com/search?l=&p=1&q=user%3Aopenclimatefix+label%3A%22good+first+issue%22&ref=advsearch&type=Issues&utf8=%E2%9C%93&state=open

You might want to consider https://github.com/openclimatefix/PVNet/pull/113

What kinda of stuff do you like doing?
