### ISSUE TITLE
Bump version not working

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_datapipes#123]
**Describe the bug**
The main branch is now protected, so the bump version bot cant push to it, to make new version

**To Reproduce**
![Screenshot 2022-12-13 at 12 49 32](https://user-images.githubusercontent.com/34686298/207322631-4bc24988-b1c1-49fc-b575-0f67f19c9afd.png)

**Expected behavior**
push to main, makes the version be bump and release to pypi

**Comment by peterdudfield** [comment]
see https://github.com/semantic-release/github/issues/175

**Comment by peterdudfield** [comment]
fancy this one @jacobbieker ?

**Comment by jacobbieker** [comment]
Yep, I got it!

**Comment by peterdudfield** [comment]
thanks

**Comment by jacobbieker** [comment]
This should fix it: https://github.com/openclimatefix/.github/pull/31

**Comment by jacobbieker** [comment]
Not sure, its a bit hard to test. I just removed the protection right now, will work on getting it working on a test repo, then update this one
