### ISSUE TITLE
Open Eumetsat-rss data error 

### ISSUE THREAD

**Issue by gitbooo** [openclimatefix/ocf_datapipes#133]
I am trying to open a file on "Eumetsat-rss" and I am getting the following error message: `codec not available: 'imagecodecs_jpegxl_float_with_nans'`. I have already installed the required packages, but I am still getting this error. Can you help me resolve this issue?

This is the code:

```
ZARR_PATH = "/Eumetsat-rss/2020_000000-of-000097.zarr.zip"
ds_from_zarr = xr.open_dataset(ZARR_PATH, mode="r", engine="zarr")
```

**Comment by jacobbieker** [comment]
Hi, so you need to add the line
```from jpeg_xl_float_with_nans import jpeg_xl_float_with_nans```

to import that codec, which then should open it
