### ISSUE TITLE
Load form PVsite database

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_datapipes#144]
## Detailed Description
Add new PV load method to load PV data from new database

## Context
For a bit, we will have `pv` that is for NIA project and a new `pvsite` database. 
This de risks breaking the NIA project database

## Possible Implementation
new method like https://github.com/openclimatefix/ocf_datapipes/blob/main/ocf_datapipes/load/pv/live.py

**Comment by dfulu** [comment]
This was completed in #226
