### ISSUE TITLE
add nan checks

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_datapipes#235]
## Detailed Description
Add checks on nwp and satellite if there are any nans

## Context
- good to check data is validate
- should we log a warning, or raise an assertion?

## Possible Implementation
- could check when we load the data, and when we have made the batches
- we should check for, nans, if all the values are exactly the same

**Comment by peterdudfield** [comment]
@jacobbieker would you be able to take this?

**Comment by jacobbieker** [comment]
Yep, I'll start working on it today

**Comment by peterdudfield** [comment]
Thanks @jacobbieker

**Comment by jacobbieker** [comment]
Finished with #236
