### ISSUE TITLE
Add unit tests for all functions

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/ocf_datapipes#24]
For PP production, all the functions are tested in the end2end test, but not all of them have individual unit tests, although most do. Would be good to have unit tests for all of them. Same for the non-production datapipes, unit tests are currently a bit spotty for them.

**Comment by peterdudfield** [comment]
Think ill close this for the moment, there's fairly good coverage (80%). We can open sepecific tests like https://github.com/openclimatefix/ocf_datapipes/issues/115
