### ISSUE TITLE
Expand README to be more informative

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/ocf_datapipes#25]
## Detailed Description
Add more on how to contribute, design decisions, visualization of how the datapipes work together

**Comment by peterdudfield** [comment]
Would good to add one or two examples perhaps, of how to use the data pipes. Just 5 lines of python, or something like that

**Comment by rjmcoder** [comment]
Hi, This is the first time I am approaching to contribute to an open source project, so pardon me if I am doing it the wrong way.
I recently came to know about Open Climate Fix and immediately decided to see if I can be of help. I have few programming languages knowledge and do it for living, and want to contribute to several of the open issues, but want to start with something small so I can understand the contribution process rather then the contribution itself.
Please let me know how can I can contribute to this issue and help close it. Thanks!

**Comment by jacobbieker** [comment]
Hi, thanks for reaching out! One thing that could be a big help is to add some simple examples to the README, potentially taking from the `tests/` so that people know how to build and use the datapipes pretty easily. That wouldn't close the whole issue, but would be a great first step! More involved would be to try to sketch out some visualizations of how the datapipes work together, which you are very welcome to tackle, and I can help with! But would be more involved.

**Comment by rjmcoder** [comment]
@jacobbieker thanks for replying! I want to be a long time contributor to this repo, so just want to know little bit of the big picture... Few questions:

- Where can I find more info on the format of the datasets? To understand them better?
- Are we thinking more in terms of contributing or using the existing data?
- In the meanwhile, I'll take a look at the `tests/`.

Thanks.

**Comment by rjmcoder** [comment]
@jacobbieker I am getting following error while setting up my environment in PyCharm with all the dependencies

![image](https://user-images.githubusercontent.com/19336259/235565602-2843f4f3-8e06-49fd-bd14-2a3301abba7b.png)


any clues??

**Comment by rjmcoder** [comment]
@jacobbieker I am getting the following error while setting up the environment in PyCharm



![image](https://user-images.githubusercontent.com/19336259/235566153-d889fcbe-d632-4698-b7a1-bcc8a06f63c9.png)

any clues??

**Comment by rjmcoder** [comment]
@jacobbieker please ignore the above error, Was able to fix it, needed to add more channels to the PyCharm manage repositories.

After carefully looking at the current Readme, I see there is already a template example for adding new data pipes. The new examples that we want to add from `tests/`would be very similar, right?

Thanks.

**Comment by jacobbieker** [comment]
Yeah, there is the example of how to add one, but more of a how-to examples of using some of the datapipes to make a pipeline would be very helpful? So maybe a very small one from `training/` for example, to show how to chain together the datapipes and use it in a dataloader. 

For your previous questions:
1. Not all the data is public, but the satellite data is public [here](https://console.cloud.google.com/marketplace/product/bigquery-public-data/eumetsat-seviri-rss-hrv-uk?project=tactile-acrobat-249716) and UK PV data [here](https://huggingface.co/datasets/openclimatefix/uk_pv), and generally we use [xarray and zarr](https://docs.xarray.dev/en/stable/) for the data in this repo. The `load/` utilities sorta show the format of the data, and the data in the test examples as well.
2. I was thinking both, we would ideally have a easy how-to to add new data sources, both for us at OCF as we add support for more NWPs and other data sources, as well as for the community! But also having more docs on how the current data is used is quite useful as well, so people can get up and running quickly with the code that is available.

Thanks again for looking at this stuff! This will be very useful!

**Comment by rjmcoder** [comment]
Hi @jacobbieker after going through the code base, I was able to create the below kind of pseudo code for someone to use and combine the existing data pipes. Hopefully this is close to what you were expecting.
Its not exactly 5 lines :grinning: but I was aspiring to give a little more detailed version. 
Let me know your thoughts.. thanks!

### The below code snippets have been picked from `ocf_datapipes\training\pv_satellite_nwp.py` file

``` python

# 1. read the configuration model for the dataset, detailing what kind of data is the dataset holding, e.g., pv, pv+satellite, pv+satellite+nwp, etc

	config_datapipe = OpenConfiguration(configuration)

# 2. create respective data pipes for pv, nwp and satellite
	
	pv_datapipe, pv_location_datapipe = (OpenPVFromNetCDF(pv=configuration.input_data.pv).pv_fill_night_nans().fork(2))

	nwp_datapipe = OpenNWP(configuration.input_data.nwp.nwp_zarr_path)

	satellite_datapipe = OpenSatellite(zarr_path=configuration.input_data.satellite.satellite_zarr_path)

# 3. pick all or random location data based on pv data pipeline
	
	location_datapipes = pv_location_datapipe.location_picker().fork(4, buffer_size=BUFFER_SIZE)

# 4. for the above picked locations get their respective spatial space slices from all the data pipes
	
	pv_datapipe, pv_time_periods_datapipe, pv_t0_datapipe = pv_datapipe.select_spatial_slice_meters(...)

	nwp_datapipe, nwp_time_periods_datapipe = nwp_datapipe.select_spatial_slice_pixels(...)

	satellite_datapipe, satellite_time_periods_datapipe = satellite_datapipe.select_spatial_slice_pixels(...)

# 5. get contiguous time period data for the above picked locations
	
	pv_time_periods_datapipe = pv_time_periods_datapipe.get_contiguous_time_periods(...)

	nwp_time_periods_datapipe = nwp_time_periods_datapipe.get_contiguous_time_periods(...)

	satellite_time_periods_datapipe = satellite_time_periods_datapipe.get_contiguous_time_periods(...)

# 6. since all the datapipes have different sampling period for their data, lets find the time that is common between all the data pipes

	overlapping_datapipe = pv_time_periods_datapipe.select_overlapping_time_slice(secondary_datapipes=[nwp_time_periods_datapipe, satellite_time_periods_datapipe])

# 7. take time slices for the above overlapping time from all the data pipes

    pv_datapipe = pv_datapipe.select_time_slice(...)

    nwp_datapipe = nwp_datapipe.convert_to_nwp_target_time(...)

    satellite_datapipe = satellite_datapipe.select_time_slice(...)

# 8. Finally join all the data pipes together

    combined_datapipe = MergeNumpyModalities([nwp_datapipe, pv_datapipe, satellite_datapipe])


```

**Comment by jacobbieker** [comment]
Thanks a lot! That looks good, and I think would be quite helpful to include. Great job breaking it down!

**Comment by rjmcoder** [comment]
Thanks! 
Will update the README and submit a PR by tomorrow.

**Comment by rjmcoder** [comment]
@jacobbieker I have opened a PR #196 with the README updates.
Feel free to let me know if more changes are needed. 
Thanks!
