### ISSUE TITLE
ECMWF cumulative variables

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_datapipes#286]
There are some variables that are cumulative. 

![Image](https://github.com/openclimatefix/ocf_datapipes/assets/34686298/20ca35f6-7622-49d4-97ea-c852e2057965)

This is quite tricky for the model to handle, as delayed in data can have a real impact. 
OF course the model should learn to take the difference but, it perhaps is easier to give the model what we want

Tasks
- add datapipes that adds/replaces variables with the diff
- [ optional] Adjust ECMWF normalisation values for diffed variables
- Retrain PVnet UK with these diffs
- Retrain Windnet with these diffs

**Comment by jacobbieker** [comment]
It seems like wind variables are not cumulative, so it shouldn't affect windnet too much, but definetly should retrain PVNet for india with it. And do diffs for all cumulative variables in the future, as I don't think any model will handle it very well, and normalization won't work very well for this

**Comment by dfulu** [comment]
This is mostly solved by #314. The only thing not covered would be to add normalisation values for the diffed ECMWF variables over India

**Comment by peterdudfield** [comment]
Shall i close this now @dfulu ?

**Comment by dfulu** [comment]
> Shall i close this now @dfulu ?

Yeh sure
