### ISSUE TITLE
Question: Using OCF Datapipes with DGMR

### ISSUE THREAD

**Issue by rutkovskii** [openclimatefix/ocf_datapipes#301]
I just discovered this repository just now. 

From what I know, it is an approach to train large models on multiple GPUs efficiently. 
I am currently working on implementing DGMR from [skillful_nowcasting](https://github.com/openclimatefix/skillful_nowcasting) on my data, but I encounter the problem of model requiring more than 80 GB available on a single A100.

Do you think this project can be used to spread out training of DGMR over several GPUs?

**Comment by jacobbieker** [comment]
Hi,

This repo won't help with that unfortunately. This is more designed for loading the data quickly/effectively across multiple different spatio-temporal datasets in a unified manner. This code should help make loading the datasets easier, but won't help with the model training. I would suggest for the DGMR model, either try smaller precision, or remove the spectral norm layers in the model, and then it should distribute across multiple GPUs easily enough

**Comment by rutkovskii** [comment]
I understand. Thank you, @jacobbieker !
