### ISSUE TITLE
Load PV data from database

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_datapipes#31]
Similar to [here](https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/data_sources/pv/live.py)

Open PV data from database 
pv_power = get_pv_power_from_database(
        history_duration=timedelta(hours=1),
        load_extra_minutes=30,
        interpolate_minutes=30,
        load_extra_minutes_and_keep=30,
    )

Options
- only load a certain amount of history
- option to load extra minutes
- option to do interpolation on data
- option to load extra minutes and keep them

Although some of these are little hacks to get the live working, for the moment, lets use these to get it working, and we can remove later

tests:
similar to https://github.com/openclimatefix/nowcasting_dataset/blob/main/tests/data_sources/pv/test_pv_live.py

**Comment by jacobbieker** [comment]
Related #22
