### ISSUE TITLE
Multie init times in example

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_datapipes#328]
## Describe the bug
When loading examples and joining together to batch, some examples have more than one init time

## To Reproduce
1. Create examples for Windnet in india
2. run model by combing the batches
```
  File "/home/peter/miniconda3/envs/pvnet/lib/python3.11/site-packages/numpy/core/shape_base.py", line 449, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
This exception is thrown by __iter__ of MapperIterDataPipe(datapipe=BatcherIterDataPipe, fn=stack_np_examples_into_batch, input_col=None, output_col=None)
```

## Expected behavior
examples should have exctaly the same shape, so they can be stacked

## Additional context
<img width="538" alt="Screenshot 2024-06-14 at 15 54 52" src="https://github.com/openclimatefix/ocf_datapipes/assets/34686298/11c44de5-b5f5-4a38-bfb9-274dd4b7a557">

## Potential Fix
- when we select the init time in the nwps, if there is more than 1, select the first
- this could be done in here https://github.com/openclimatefix/ocf_datapipes/blob/main/ocf_datapipes/select/select_time_slice_nwp.py#L156
- if len(xr_data.init_time_utc) > 1: xr_data = xr_data.isel(init_time_utc=0) (or something like that)

**Comment by peterdudfield** [comment]
The error could be here - https://github.com/openclimatefix/ocf_datapipes/blob/main/ocf_datapipes/utils/utils.py#L194

**Comment by peterdudfield** [comment]
Seems to always be 50, with 1 init time different, and then 49 of the first init time + 12 hours

**Comment by dfulu** [comment]
@peterdudfield I believe this is almost the desired behaviour. Basically for each requested valid time, we select data from the most recent init time before it. For example, the init time t0 is 13:00, and we want to slice data from 2 hours before t0 up to 48 hours ahead. For ECMWF the available init times would be 00:00 and 12:00. So for the 2 hours before we select:

- The +11 hours step from the 00:00 forecast (valid at 11:00)
- The +0 hour step from the 12:00 forecast (valid at 12:00)

Then also select the +1 to +49 hours steps from the 12:00 forecast. So in this case the init times should be 00:00 for the first step and 12:00 for the remaining 50 steps.

I would guess your error is an edge case coming from somewhere else. It would depend on maximum forecast horizon of the ECMWF training data, the amount of NWP history and forecast, and the presumed delay of the NWP

**Comment by peterdudfield** [comment]
ah that make sense, perhaps we need to make sure the init times are unique then? 

but yea, your write, my error, seems perhaps to sit somewhere else

**Comment by dfulu** [comment]
I presume the init-times are unique in the data you are slicing from. The init times you showed above are the init-times associated with each valid time sliced from the data.

I.e. in the example I gave above you'd get the valid times:

`11:00, 12:00, 13:00, 14:00 ...`

and the init time for each of these:

`00:00, 12:00, 12:00, 12:00 ...`

So I think this part of it is fine

**Comment by peterdudfield** [comment]
Ah thanks @dfulu, so somwhere in ocf_datapipes we have must have a function that flatterns these? Do you know where?

**Comment by dfulu** [comment]
Yeh it is [select_time_slice_nwp()](https://github.com/openclimatefix/ocf_datapipes/blob/main/ocf_datapipes/select/select_time_slice_nwp.py#L66)

**Comment by peterdudfield** [comment]
ah yea thanks, but ive got a problem, when batches are made. If one batch has init times of constant, and one is a vector, then it cant merge them together, or throughs an error. Im suprised this hasnt come up before as I cant see that windnet is a special case

**Comment by peterdudfield** [comment]
So perhaps the question, should be one do 95% of my batches only contain 1 init time

<img width="415" alt="Screenshot 2024-06-19 at 14 28 34" src="https://github.com/openclimatefix/ocf_datapipes/assets/34686298/30573383-56b0-4d34-9748-833c25d3a2a2">, where it should perhpas be a vector that is repeated

**Comment by peterdudfield** [comment]
It turns out it is not in `select_time_slice_nwp`, ill keep looking for the bug

**Comment by peterdudfield** [comment]
Something happens in https://github.com/openclimatefix/ocf_datapipes/blob/main/ocf_datapipes/utils/utils.py#L149

**Comment by peterdudfield** [comment]
This should solve it #333
