### ISSUE TITLE
Set Database logging output to Debug instead of info by default

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/ocf_datapipes#49]
## Detailed Description
It's somewhat hard to see other logs with how many things are outputted in the tests for the database setup and commits. Setting those to debug might make it a bit easier to see what actually going on.

**Comment by jacobbieker** [comment]
Done in the test script now in #48

**Comment by peterdudfield** [comment]
Have to set `echo=False` when connecting to the database, perhaps this is in `conftest.py`
