### ISSUE TITLE
Add validation on Location object

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_datapipes#56]
Add validation on [Location](https://github.com/openclimatefix/ocf_datapipes/blob/main/ocf_datapipes/utils/consts.py#L144) object. 

Currently the location are in osgb mapping, so should check 
x>0, x < need to look up
y>0, y < need to look up

**Comment by rjmcoder** [comment]
Hi @peterdudfield is this still open, I would like to work on it, thanks.

**Comment by peterdudfield** [comment]
Yea, this would be amazing

**Comment by rjmcoder** [comment]
Thanks, will start working on this once I am done with #25.

**Comment by rjmcoder** [comment]
@peterdudfield I was looking where the Location object is getting instantiated, seems like its done in `ocf_datapipes/select/location_picker.py`, so should we just `continue` if the `location.x` or `location.y` is < 0 ?
and also, sorry, but couldn't understand what do you mean by "need to look up" in your original comment "x or y < need to look up" ?

Thanks.

**Comment by peterdudfield** [comment]
I think it would be great to use pydantic (validators)[https://docs.pydantic.dev/latest/usage/validators/]

Ah yea I need to look up the maximum values, this website gives both the maximum and the minimum - https://epsg.io/27700

**Comment by peterdudfield** [comment]
As a bonus you could put a extra field saying
`coordinate_system' which could only be `osgb` or `lat_lon`, 

And then validating if its `lat_lon` would be -180 <x< 180 and -90 < y< 90 ( i think)

**Comment by rjmcoder** [comment]
@peterdudfield sorry wasn't aware of pydantic for validation, good to know about it.
I'll use that and also add another field for `coordinate_system`

From the website, looks like below are the bounds:
Projected bounds:
-103976.3 -16703.87 
652897.98 1199851.44

And based on the Center coordinates of 305371.94    610575.38
looks like 
-103976.3 < x < 652897.98
-16703.87 < y < 1199851.44

If my above understanding of the bounds is correct, then looks like x and y both can take values < 0, but in your original message you want to make sure they are > 0? 
Could you please explain a little more here, sorry, if I am missing something here.
Thanks.

**Comment by peterdudfield** [comment]
> @peterdudfield sorry wasn't aware of pydantic for validation, good to know about it. I'll use that and also add another field for `coordinate_system`
> 
> From the website, looks like below are the bounds: Projected bounds: -103976.3 -16703.87 652897.98 1199851.44
> 
> And based on the Center coordinates of 305371.94 610575.38 looks like -103976.3 < x < 652897.98 -16703.87 < y < 1199851.44
> 
> If my above understanding of the bounds is correct, then looks like x and y both can take values < 0, but in your original message you want to make sure they are > 0? Could you please explain a little more here, sorry, if I am missing something here. Thanks.

Yea please use the bounds you have found, not `>0`

**Comment by rjmcoder** [comment]
Thanks @peterdudfield 

I have made the below updates to the `ocf_datapipes/utils/consts.py` file:
- Added a new optional field named `coordinate_system`, it defaults to `osgb`
- Added validators for `coordinate_system`, `x` and `y`.
- Based on the chosen `coordinate_system` the min/max values for `x` and `y` will be different.

Now for testing:
- Since I am not familiar with the entire code base, could you please help check if this looks good?
- What test(s) can I run to make sure this will not blow up something else somewhere?
- And any other checks we need to make?

```python
class Location(BaseModel):
    """Represent a spatial location."""

    x: float
    y: float
    id: Optional[int]
    coordinate_system: Optional[str] = "osgb"   # ["osgb", "lat_lon"]

    @validator("coordinate_system")
    def validate_coordinate_system(cls, v):
        """Validate 'coordinate_system'"""
        allowed_coordinate_systen = ["osgb", "lat_lon"]
        if v not in allowed_coordinate_systen:
            raise ValueError(f"coordinate_system = {v} is not in {allowed_coordinate_systen}")
        return v

    @validator("x")
    def validate_x(cls, v):
        """Validate 'x'"""
        min_x: float
        max_x: float
        if coordinate_system == "osgb":
            min_x, max_x = -103976.3, 652897.98
        if coordinate_system == "lat_lon":
            min_x, max_x = -180, 180
        if v < min_x or v > max_x:
            raise ValueError(f"x = {v} must be within {[min_x, max_x]} for {coordinate_system} coordinate system")
        return v

    @validator("y")
    def validate_x(cls, v):
        """Validate 'y'"""
        min_y: float
        max_y: float
        if coordinate_system == "osgb":
            min_y, max_y = -16703.87, 1199851.44
        if coordinate_system == "lat_lon":
            min_y, max_y = -90, 90
        if v < min_y or v > max_y:
            raise ValueError(f"y = {v} must be within {[min_y, max_y]} for {coordinate_system} coordinate system")
        return v
```
Thanks!

**Comment by peterdudfield** [comment]
Yea that looks really good. Thanks for doing this

Test can be just to 
1. make a validate osgb object 
2. make a validate lat/lon object
3. make a invalid osgb x object and see if you get an error
4. make a invalid osgb y object and see if you get an error
5 make a invalid lat_lon x object and see if you get an error
6. make a invalid lat_lon y object and see if you get an error
7. Make invalid "coordinate_system" and check you get an error
+ any extras you want

The other CI tests will check that your code doesnt blow things up

**Comment by rjmcoder** [comment]
Thanks @peterdudfield !

- Is there some reference code/tests in the codebase that I can refer to, to write these tests, that way I can follow the same standards.
- Also, once I write the tests, do I need to upload the tests as well to the codebase with my PR? If yes, which directory under `tests` should these go in?

**Comment by rjmcoder** [comment]
Yes, thanks!
another issue that I keep encountering is, whenever I try to run any tests, even the already existing ones, it gives me this error.

![image](https://github.com/openclimatefix/ocf_datapipes/assets/19336259/b19bae0d-7e17-418c-ab0a-752f6b458ca8)

As far as I know `dict` are not subscriptable, so the error makes sense to me, but knowing this code base is functional this must have worked. So, am I missing something?

The `typing` module has `Dict` (upper case "D") in it and that it subscriptable, but then `Dict` is not imported in this `consts.py` file.
So, I am wondering how was this code run before without running into this error.

Appreciate your help in helping me understand this, thanks.

**Comment by peterdudfield** [comment]
What python version are you using? I think those features come in with python >=3.10

**Comment by rjmcoder** [comment]
I am using 3.8 since the `.readthedocs.yml` file says so..
![image](https://github.com/openclimatefix/ocf_datapipes/assets/19336259/4cf53aa8-8281-4ce7-bff8-13ad09b91ed1)

**Comment by rjmcoder** [comment]
understood, no worries, let me give 3.10 a try...

**Comment by peterdudfield** [comment]
Thanks @rjmcoder

**Comment by rjmcoder** [comment]
@peterdudfield Python 3.10 worked, thanks.
I have some of the tests working, finishing up the remaining ones.. shooting to submit a PR by sometime next week.

**Comment by rjmcoder** [comment]
@peterdudfield I have raised a PR #201 with the fixes.
Feel free to let me know if more changes are needed.
Thanks!
