### ISSUE TITLE
Satellite 1 D dimensions option

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_datapipes#57]
Have the option to load Satellite data with X and Y dimesions of 1 dimension . This is how the current nowcasting Satellite consumer is set up. The more upto date satelilte data used for training PP, has2 diminsion coordaite data. I.e the Image is a sqaure. 

Perhaps this can be done in the Satellite consumer load bit, and the 1D coordates can be exapnded to 2D using 
```xx, yy = np.meshgrid(x, y, indexing='ij')```

**Comment by jacobbieker** [comment]
Do you mean for OSGB coordinates? Or the geostationary ones? Geostationary ones should be 1D, and I believe are? OSGB ones, if they are 1D, then are wrong, as the satellite pixels don't map to a regular OSGB grid, and have to already be 2D. If they are 1D, and we use meshgrid, then they will result in pixels being off by potentially a few hundred miles.

**Comment by peterdudfield** [comment]
https://github.com/openclimatefix/ocf_datapipes/blob/main/ocf_datapipes/load/satellite.py#L79

Yea for the OSGB coordinates. 

The current Satellite consumer as 1D OSGB coordinates. 

Perhaps we need then to save both 1D and 2D OSGB coordinates in the satellite consumer, this would mean the current model doesnt break

**Comment by jacobbieker** [comment]
Hmmm, okay, the ones in the consumer should also be 2D, they are set here: https://github.com/openclimatefix/Satip/blob/bc27f11849aa5f18c306cdbecffbd78f37e47438/satip/utils.py#L293-L306 as 2D coordinates, referencing the geostationary ones.

**Comment by peterdudfield** [comment]
ah ok, then maybe i was thinking of the NWP ones, ok, ill adjust the pytest accordingly and close this issue
