### ISSUE TITLE
Add GSP national pipeline

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_datapipes#64]
## Detailed Description
Add a pipeline that loads GSP national data. 

## Context
Useful for modelling PV national modelling
Dont need a spacial slice. 
Might want to reduce NWP to 20KM grid, this would 100 smaller than large 1TB file

## Possible Implementation
- Load GSP, but only national data
- Load NWP data
- merge time periods
- pick random time period

Later
- add satellite data, as we are aiming to do a National forecast for +36 hours, where satellite data will be less useful
- add pv data, as we are aiming to do a National forecast for +36 hours, where satellite data will be less useful

**Comment by peterdudfield** [comment]
Ive added this to https://github.com/openclimatefix/ocf_datapipes/blob/main/ocf_datapipes/training/gsp_national.py. This only loads GSP and NWP data. @jacobbieker you might want to use this and expand it to use pv and satellite data

**Comment by peterdudfield** [comment]
Or perhaps leave this one, and add another data pipeline. Then this can be used to benchmark

**Comment by jacobbieker** [comment]
Sounds good! I'm adding this in #69
