### ISSUE TITLE
Add Data Corruption DataPipelets

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/ocf_datapipes#7]
## Detailed Description
E.g. randomly zero out 45min of GSP data or PV data, drop the last N frames of the satellite data, etc.

**Comment by JackKelly** [comment]
One small request would be that, for GSP or PV data, maybe the "random corruptor" could set GSP or PV data to NaN; and then a subsequent DataPipelet could convert NaN to 0 (if necessary). The reason I suggest this is that, hopefully, a future version of Power Perceiver would be able to handle NaN data by masking the attention matrix where there are NaNs.
