### ISSUE TITLE
Add train/val split to data pipline

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_datapipes#73]
## Detailed Description
Split the datatimes depending if 'tra','val' or 'test'.

## Context
Need to think if we should have this split datetimes as an input to the date pipline, so we can have a train and validation datapipleline

## Possible Implementation
Code in [nowcasting_datasetis](https://github.com/openclimatefix/nowcasting_dataset/tree/main/nowcasting_dataset/dataset/split) ready to go.

**Comment by jacobbieker** [comment]
I've added a version in #74 that can split based off a date range, so e.g. 2020 for training, 2021 for testing. Doesn't work with other methods though.

**Comment by peterdudfield** [comment]
great thanks @jacobbieker , at least getting the trianing and testing split working is very useful
