### ISSUE TITLE
Update to torch 

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_datapipes#81]
Update to torch 0.13.0 and torchdata 0.5.0

its currently pinned in the requirements

**Comment by jacobbieker** [comment]
Release notes on the new version: https://github.com/pytorch/data/releases

**Comment by jacobbieker** [comment]
There doesn't seem to be any backwards breaking changes that should affect us, but I'll look into it more

**Comment by peterdudfield** [comment]
CI tests take a very long time / dont pass. Ive see it run out of memory before

**Comment by jacobbieker** [comment]
https://discuss.pytorch.org/t/torchdata-0-5-0-is-seemingly-a-lot-slower-and-more-memory-usage-than-0-4-1/166743 is a discussion about it

**Comment by peterdudfield** [comment]
Thanks @jacobbieker for raising it on there

**Comment by peterdudfield** [comment]
Moved to https://github.com/pytorch/data/issues/865
